# Soadium OS Installer Configuration

modules-search: [ local ]

instances:
- id:       users
  module:   users
  config:   users.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - users
  - networkcfg
  - hwclock
  - services-systemd
  - grub
  - umount
- show:
  - finished

branding: soadium
prompt-install: true
dont-chroot: false
